volumes:
  db_data:

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_HOST: db
  DATABASE_NAME: vapor_database
  DATABASE_USERNAME: vapor_username
  DATABASE_PASSWORD: vapor_password

services:
  app:
    image: rata-backend:latest
    build:
      context: BackendDockerfile
    environment:
      <<: *shared_environment
    depends_on:
      - db
      - validator  # Add dependency on Python validator
    ports:
      - '8080:8080'
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

  migrate:
    image: rata-backend:latest
    build:
      context: BackendDockerfile
    environment:
      <<: *shared_environment
    depends_on:
      - db
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0

  revert:
    image: rata-backend:latest
    build:
      context: BackendDockerfile
    environment:
      <<: *shared_environment
    depends_on:
      - db
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0

  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: vapor_username
      POSTGRES_PASSWORD: vapor_password
      POSTGRES_DB: vapor_database
    ports:
      - '5432:5432'

  validator:  # Python FastAPI validator service
    build:
      context: ./Rata_Scripts/ScriptsDockerfile  # keyword_detector.py is in ./Rata_Scripts directory, Dockerfile has unique name
    container_name: python-validator
    ports:
      - '8000:8000'
